config/routes.rb
Rails.application.routes.draw do

 root to: "homes#index"

  devise_for :users

  resources :appointments
  resources :join_table_user_swimming_pools
  resources :lessons
  resources :swimming_pools
  resources :profils
  resources :homes, only: [:index]
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :user
  belongs_to :lesson
end

app/models/join_table_user_swimming_pool.rb
class JoinTableUserSwimmingPool < ApplicationRecord
  belongs_to :user
  belongs_to :swimming_pool

end

app/models/lesson.rb
class Lesson < ApplicationRecord
  has_many :appointments
  has_many :users, through: :appointments
end

app/models/swimming_pool.rb
class SwimmingPool < ApplicationRecord
  has_many :join_table_user_swimming_pools
  has_many :users, through: :join_table_user_swimming_pools
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :appointments
  has_many :lessons, through: :appointments
  has_many :join_table_user_swimming_pools
  has_many :swimming_pools, through: :join_table_user_swimming_pools
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/join_table_user_swimming_pools_controller.rb
class JoinTableUserSwimmingPoolsController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/profils_controller.rb
class ProfilsController < ApplicationController
  before_action :set_profil, only: [:show, :edit, :update, :destroy]
  def index
  end

  def show
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def set_profil
    @profil = User.find(params[:id])
  end
end

app/controllers/swimming_pools_controller.rb
class SwimmingPoolsController < ApplicationController
before_action :set_swimming_pool, only: [:show, :edit, :update, :destroy]

  def index
    @swimming_pools = SwimmingPool.all
  end

  def show
  end

  def new
    @swimming_pool = SwimmingPool.new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def set_swimming_pool
    @swimming_pool = SwimmingPools.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/join_table_user_swimming_pools_helper.rb
module JoinTableUserSwimmingPoolsHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/profils_helper.rb
module ProfilsHelper
end

app/helpers/swimming_pools_helper.rb
module SwimmingPoolsHelper
end

app/views/appointments/create.html.erb
<h1>Appointments#create</h1>
<p>Find me in app/views/appointments/create.html.erb</p>

app/views/appointments/destroy.html.erb
<h1>Appointments#destroy</h1>
<p>Find me in app/views/appointments/destroy.html.erb</p>

app/views/appointments/edit.html.erb
<h1>Appointments#edit</h1>
<p>Find me in app/views/appointments/edit.html.erb</p>

app/views/appointments/index.html.erb
<h1>Appointments#index</h1>
<p>Find me in app/views/appointments/index.html.erb</p>

app/views/appointments/new.html.erb
<h1>Appointments#new</h1>
<p>Find me in app/views/appointments/new.html.erb</p>

app/views/appointments/show.html.erb
<h1>Appointments#show</h1>
<p>Find me in app/views/appointments/show.html.erb</p>

app/views/appointments/update.html.erb
<h1>Appointments#update</h1>
<p>Find me in app/views/appointments/update.html.erb</p>

app/views/homes/index.html.erb
<h1>Landing page</h1>
<p>Find me in app/views/homes/show.html.erb</p>

<%= link_to "Liste de RDV", appointments_path %>
<%= link_to "Liste des cours", lessons_path %>
<%= link_to "Liste des piscines", swimming_pools_path %>

app/views/homes/show.html.erb
<h1>Landing page</h1>
<p>Find me in app/views/homes/show.html.erb</p>

<%= link_to "Liste de RDV", appointments_path %>
<%= link_to "Liste des cours", lessons_path %>
<%= link_to "Liste des piscines", swimming_pools_path %>

app/views/join_table_user_swimming_pools/create.html.erb
<h1>JoinTableUserSwimmingPools#create</h1>
<p>Find me in app/views/join_table_user_swimming_pools/create.html.erb</p>

app/views/join_table_user_swimming_pools/destroy.html.erb
<h1>JoinTableUserSwimmingPools#destroy</h1>
<p>Find me in app/views/join_table_user_swimming_pools/destroy.html.erb</p>

app/views/join_table_user_swimming_pools/edit.html.erb
<h1>JoinTableUserSwimmingPools#edit</h1>
<p>Find me in app/views/join_table_user_swimming_pools/edit.html.erb</p>

app/views/join_table_user_swimming_pools/index.html.erb
<h1>JoinTableUserSwimmingPools#index</h1>
<p>Find me in app/views/join_table_user_swimming_pools/index.html.erb</p>

app/views/join_table_user_swimming_pools/new.html.erb
<h1>JoinTableUserSwimmingPools#new</h1>
<p>Find me in app/views/join_table_user_swimming_pools/new.html.erb</p>

app/views/join_table_user_swimming_pools/show.html.erb
<h1>JoinTableUserSwimmingPools#show</h1>
<p>Find me in app/views/join_table_user_swimming_pools/show.html.erb</p>

app/views/join_table_user_swimming_pools/update.html.erb
<h1>JoinTableUserSwimmingPools#update</h1>
<p>Find me in app/views/join_table_user_swimming_pools/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Alleau</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </head>

  <body>
    <ul>
      <li>
      <%= link_to "Home", homes_path %>
    </li>
  <% if user_signed_in? %>
    <li>
      <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
    </li>

    <li>
      Voici ton email : <%= current_user.email %>
    </li>

    <li>
      <%= link_to "Profil", profil_path(current_user) %>
    </li>

  <% else %>
    <li>    
      <%= link_to "Sign in", new_user_session_path %>
    </li>

    <li>
      <%= link_to "Sign up", new_user_registration_path %>
    </li>

  <% end %>
</ul>
    <%= yield %>
  </body>
</html>

app/views/lessons/create.html.erb
<h1>Lessons#create</h1>
<p>Find me in app/views/lessons/create.html.erb</p>

app/views/lessons/destroy.html.erb
<h1>Lessons#destroy</h1>
<p>Find me in app/views/lessons/destroy.html.erb</p>

app/views/lessons/edit.html.erb
<h1>Lessons#edit</h1>
<p>Find me in app/views/lessons/edit.html.erb</p>

app/views/lessons/index.html.erb
<h1>Lessons#index</h1>
<p>Find me in app/views/lessons/index.html.erb</p>



<ol>
<li><%= link_to "Aquagym", lessons_path %></li>
<li><%= link_to "Aquabike", lessons_path %></li>
<li><%= link_to "Aquarunning", lessons_path %></li>
<li><%= link_to "Aquabody", lessons_path %></li>
<li><%= link_to "Aquapunching", lessons_path %></li>
<li><%= link_to "Cours de natation", lessons_path %></li> 
<li><%= link_to "Bébés nageurs", lessons_path %></li>
</ol>

app/views/lessons/new.html.erb
<h1>Lessons#new</h1>
<p>Find me in app/views/lessons/new.html.erb</p>

app/views/lessons/show.html.erb
<h1>Lessons#show</h1>
<p>Find me in app/views/lessons/show.html.erb</p>

app/views/lessons/update.html.erb
<h1>Lessons#update</h1>
<p>Find me in app/views/lessons/update.html.erb</p>

app/views/profils/create.html.erb
<h1>Profils#create</h1>
<p>Find me in app/views/profils/create.html.erb</p>

app/views/profils/destroy.html.erb
<h1>Profils#destroy</h1>
<p>Find me in app/views/profils/destroy.html.erb</p>

app/views/profils/edit.html.erb
<h1>Profils#edit</h1>
<p>Find me in app/views/profils/edit.html.erb</p>

app/views/profils/index.html.erb
<h1>Profils#index</h1>
<p>Find me in app/views/profils/index.html.erb</p>

app/views/profils/new.html.erb
<h1>Profils#new</h1>
<p>Find me in app/views/profils/new.html.erb</p>

app/views/profils/show.html.erb
<h1>Profils#show</h1>
<p>Find me in app/views/profils/show.html.erb</p>

<%= link_to "Edit email / password", edit_user_registration_path %>

app/views/profils/update.html.erb
<h1>Profils#update</h1>
<p>Find me in app/views/profils/update.html.erb</p>

app/views/swimming_pools/create.html.erb
<h1>SwimmingPools#create</h1>
<p>Find me in app/views/swimming_pools/create.html.erb</p>

app/views/swimming_pools/destroy.html.erb
<h1>SwimmingPools#destroy</h1>
<p>Find me in app/views/swimming_pools/destroy.html.erb</p>

app/views/swimming_pools/edit.html.erb
<h1>SwimmingPools#edit</h1>
<p>Find me in app/views/swimming_pools/edit.html.erb</p>

app/views/swimming_pools/index.html.erb
<h1>SwimmingPools#index</h1>
<p>Find me in app/views/swimming_pools/index.html.erb</p>

<% if user_signed_in? %>

<%= link_to "Ajouter votre piscine", new_swimming_pool_path %>

<% end %>

app/views/swimming_pools/new.html.erb
<h1>SwimmingPools#new</h1>
<p>Find me in app/views/swimming_pools/new.html.erb</p>

<div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <br><br><br>
      <%= form_for @swimming_pool do |f| %>
        <h1 class="h3 mb-3 font-weight-normal text-center">Sign up</h1>
        <div class="form-group">
          <%= f.label :name, "Nom" %><br />
          <%= f.text_field :name, autocomplete: "name", class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :adress, "Rue" %>
          <%= f.text_field :adress, autocomplete: "adress", class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :city %><br />
          <%= f.text_field :city, autocomplete: "city", class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :zipcode, "Code postal" %><br />
          <%= f.text_field :zipcode, autocomplete: "zipcode", class: "form-control" %>
        </div>
        <div class="actions mt-5">
          <%= f.submit "Ajouter sa piscine", class: "btn btn-lg btn-primary btn-block" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/swimming_pools/show.html.erb
<h1>SwimmingPools#show</h1>
<p>Find me in app/views/swimming_pools/show.html.erb</p>

app/views/swimming_pools/update.html.erb
<h1>SwimmingPools#update</h1>
<p>Find me in app/views/swimming_pools/update.html.erb</p>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>